# Generated by Django 3.1.5 on 2021-01-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.CharField(default='abc', max_length=2083),
        ),
    ]
