# Generated by Django 3.1.5 on 2021-01-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Client Category: '),
        ),
    ]
