# Generated by Django 3.1.5 on 2021-01-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20210126_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='category',
        ),
    ]
