# Generated by Django 3.1.5 on 2021-01-26 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.clientcategory', verbose_name='Client Category'),
        ),
    ]
