# Generated by Django 3.1.5 on 2021-01-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20210126_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sortOrder',
            field=models.IntegerField(default=10, verbose_name='Sort Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.CharField(default='No Logo', max_length=2083),
        ),
    ]
