# Generated by Django 3.1.5 on 2021-01-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20210126_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sortOrder'], 'verbose_name_plural': 'Categories'},
        ),
    ]
