# Generated by Django 3.1.5 on 2021-02-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasofoperations',
            name='description',
            field=models.TextField(default='Enter description...', max_length=2000),
        ),
    ]
