# Generated by Django 3.1.5 on 2021-02-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_areasofoperations_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areasofoperations',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Areas of Operations'},
        ),
        migrations.AlterModelOptions(
            name='operations',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Operations'},
        ),
        migrations.AddField(
            model_name='areasofoperations',
            name='sort_order',
            field=models.IntegerField(default=10, verbose_name='Sort Order'),
        ),
    ]
